server:
  port: 8080
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,application/javascript,text/plain,text/css,text/javascript
project:
  rest.pkg: com.synto.im,com.synto.core

im:
  version:
    server: 2.1.3
    softwarecenter: http://192.168.1.15:8000/imdownload

#上传文件
file:
  root: /opt/fileserver/im
  downloadUrl: http://192.168.1.15:8000/syntoimdownload
  photo: /opt/fileserver/imphoto
  photoUrl: http://192.168.1.15:8000/syntoimphoto

#消息服务配置
openfire:
  url: http://localhost
  port: 9090

#定时任务
task:
  delete-file:
    cron: 0 0 1 * * ?
    day: 7

spring:
  jersey.application-path: /rest
  jpa:
    show-sql: true
    properties.hibernate:
       hbm2ddl.auto: update
       dialect: org.hibernate.dialect.OscarDialect
#       dialect: org.hibernate.dialect.MySQL5InnoDBDialect
  datasource:
    driver-class-name: com.oscar.Driver
    url: jdbc:oscar://10.254.1.130:2020/stjstx
    username: SYSDBA
    password: szoscar55
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/demo?serverTimezone=PRC
#    username: root
#    password: root
    hikari:
      connection-test-query: SELECT 1 FROM DUAL
      connection-timeout: 30000
      maximum-pool-size: 20
      max-lifetime: 1800000
      minimum-idle: 5
  redis:
    #数据库索引
    database: 2
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大阻塞等待时间(负数表示没限制)
        max-wait: -1
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
    #连接超时时间
    timeout: 10000

logging:
  path: ../log
  level:
    root: INFO
    org.springframework.boot: INFO
    org.camunda: INFO
    org.hibernate: INFO
    org.apache.shiro: INFO
